backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "settings/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }

  - name: "general"
    label: "General Settings"
    file: "settings/general.json"
    fields:
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Phone", name: "phone", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }

  - name: "design"
    label: "Design Settings"
    file: "settings/design.json"
    fields:
      - { label: "Hero Section Background", name: "hero_bg", widget: "image" }
      - { label: "Hero Section Color", name: "hero_color", widget: "color" }
      - { label: "Products Section Background", name: "products_bg", widget: "image" }
      - { label: "Products Section Color", name: "products_color", widget: "color" }
